const self = {
    items: () => {
        return [
            {value: 'Absolutely'},
            {value: 'Achoo'},
            {value: 'Ack'},
            {value: 'Adios'},
            {value: 'Aha'},
            {value: 'Ahoy'},
            {value: 'Agreed'},
            {value: 'Alack'},
            {value: 'Alright'},
            {value: 'Alrighty'},
            {value: 'Alrighty-roo'},
            {value: 'Alack'},
            {value: 'Alleluia'},
            {value: 'All hail'},
            {value: 'Aloha'},
            {value: 'Amen'},
            {value: 'Anytime'},
            {value: 'Argh'},
            {value: 'Anyhoo'},
            {value: 'Anyhow'},
            {value: 'As if'},
            {value: 'Attaboy'},
            {value: 'Attagirl'},
            {value: 'Awww'},
            {value: 'Awful'},
            {value: 'Ay'},
            {value: 'Bam'},
            {value: 'Bah hambug'},
            {value: 'Begorra'},
            {value: 'Behold'},
            {value: 'Bingo'},
            {value: 'Blah'},
            {value: 'Bravo'},
            {value: 'Brrr'},
            {value: 'Bye'},
            {value: 'Cheers'},
            {value: 'Ciao'},
            {value: 'Cripes'},
            {value: 'Crud'},
            {value: 'Darn'},
            {value: 'Dear'},
            {value: 'Doh'},
            {value: 'Drat'},
            {value: 'Eek'},
            {value: 'Encore'},
            {value: 'Eureka'},
            {value: 'Fiddlesticks'},
            {value: 'Fie'},
            {value: 'Gadzooks'},
            {value: 'Gee'},
            {value: 'Geepers'},
            {value: 'Gee Whiz'},
            {value: 'Golly'},
            {value: 'Goodbye'},
            {value: 'Goodness'},
            {value: 'Goodness Gracious'},
            {value: 'Gosh'},
            {value: 'Great'},
            {value: 'Ha'},
            {value: 'Ha-ha'},
            {value: 'Hail'},
            {value: 'Hallelujah'},
            {value: 'Heigh-ho'},
            {value: 'Hello'},
            {value: 'Hey'},
            {value: 'Hi'},
            {value: 'Holy cow'},
            {value: 'Holy smokes'},
            {value: 'Hotdog'},
            {value: 'Huh'},
            {value: 'Hurray'},
            {value: 'Hush'},
            {value: 'Indeed'},
            {value: 'Jeepers creepers'},
            {value: 'Lo and behold'},
            {value: 'Man'},
            {value: 'My word'},
            {value: 'No'},
            {value: 'Now'},
            {value: 'Nah'},
            {value: 'Oh'},
            {value: 'Oh my'},
            {value: 'Oh well'},
            {value: 'Ooh'},
            {value: 'Ouch'},
            {value: 'Ow'},
            {value: 'Phooey'},
            {value: 'Please'},
            {value: 'Pooh'},
            {value: 'Pow'},
            {value: 'Presto'},
            {value: 'Pshaw'},
            {value: 'Rats'},
            {value: 'Right-o'},
            {value: 'Scat'},
            {value: 'Shh'},
            {value: 'Shoo'},
            {value: 'Shucks'},
            {value: 'So'},
            {value: 'So long'},
            {value: 'Thanks'},
            {value: 'There'},
            {value: 'Touché'},
            {value: 'Ugh'},
            {value: 'Uh-huh'},
            {value: 'Uh-oh'},
            {value: 'Ugh'},
            {value: 'Viva'},
            {value: 'Voila'},
            {value: 'Waa'},
            {value: 'Wahoo'},
            {value: 'Well'},
            {value: 'Whoopee'},
            {value: 'Whoops'},
            {value: 'Whoosh'},
            {value: 'Wow'},
            {value: 'Yay'},
            {value: 'Yea'},
            {value: 'Yes'},
            {value: 'Yikes'},
            {value: 'Yippee'},
            {value: 'Yo'},
            {value: 'Yuck'},
            {value: 'Yummy'},
            {value: 'Zap'},
        ];
    }
};

module.exports = self;